// <auto-generated />
using System;
using CarRentalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApi.Data.Migrations
{
    [DbContext(typeof(VehicleRentalContext))]
    [Migration("20260127222524_Migration-2701-1")]
    partial class Migration27011
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("CustomerAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CustomerDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerAddressId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CarRentalApi.Models.CustomerAddress", b =>
                {
                    b.Property<int>("CustomerAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerAddressId"));

                    b.Property<string>("CustomerAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddress2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddressCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddressCounty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddressPostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerAddressId");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("CarRentalApi.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("VehicleColour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("VehicleCostPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleBooking", b =>
                {
                    b.Property<int>("VehicleBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleBookingId"));

                    b.Property<DateTime>("BookingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleBookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleBooking");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleDamage", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleDamageTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleBookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VehicleDamageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VehicleId", "VehicleDamageTypeId", "CustomerId", "VehicleBookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleDamageTypeId");

                    b.ToTable("VehicleDamage");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleDamageType", b =>
                {
                    b.Property<int>("VehicleDamageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleDamageTypeId"));

                    b.Property<string>("VehicleDamageTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleDamageTypeId");

                    b.ToTable("VehicleDamageType");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleHistory", b =>
                {
                    b.Property<int>("VehicleHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleHistoryId"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VehicleHistoryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleHistoryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleHistory");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleLocation", b =>
                {
                    b.Property<int>("VehicleLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleLocationId"));

                    b.Property<string>("VehicleLocationAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleLocationAddress2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleLocationCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleLocationCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleLocationCounty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleLocationPostcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleLocationId");

                    b.ToTable("VehicleLocation");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehiclePrice", b =>
                {
                    b.Property<int>("VehiclePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiclePriceId"));

                    b.Property<decimal>("VehicleDailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VehiclePriceDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VehiclePriceDateTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehiclePriceId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehiclePrice");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<int>("VehicleLocationId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleQuantity")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleTypeId");

                    b.HasIndex("VehicleLocationId");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("CarRentalApi.Models.Customer", b =>
                {
                    b.HasOne("CarRentalApi.Models.CustomerAddress", "CustomerAddress")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerAddress");
                });

            modelBuilder.Entity("CarRentalApi.Models.Vehicle", b =>
                {
                    b.HasOne("CarRentalApi.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleBooking", b =>
                {
                    b.HasOne("CarRentalApi.Models.Customer", "Customer")
                        .WithMany("VehicleBookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApi.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleBookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleDamage", b =>
                {
                    b.HasOne("CarRentalApi.Models.Customer", "Customer")
                        .WithMany("VehicleDamages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApi.Models.VehicleDamageType", "VehicleDamageType")
                        .WithMany("VehicleDamages")
                        .HasForeignKey("VehicleDamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApi.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleDamages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleDamageType");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleHistory", b =>
                {
                    b.HasOne("CarRentalApi.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleHistories")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehiclePrice", b =>
                {
                    b.HasOne("CarRentalApi.Models.VehicleType", "VehicleType")
                        .WithMany("VehiclePrices")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleType", b =>
                {
                    b.HasOne("CarRentalApi.Models.VehicleLocation", "VehicleLocation")
                        .WithMany("VehicleTypes")
                        .HasForeignKey("VehicleLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleLocation");
                });

            modelBuilder.Entity("CarRentalApi.Models.Customer", b =>
                {
                    b.Navigation("VehicleBookings");

                    b.Navigation("VehicleDamages");
                });

            modelBuilder.Entity("CarRentalApi.Models.CustomerAddress", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CarRentalApi.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleBookings");

                    b.Navigation("VehicleDamages");

                    b.Navigation("VehicleHistories");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleDamageType", b =>
                {
                    b.Navigation("VehicleDamages");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleLocation", b =>
                {
                    b.Navigation("VehicleTypes");
                });

            modelBuilder.Entity("CarRentalApi.Models.VehicleType", b =>
                {
                    b.Navigation("VehiclePrices");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
